#!/bin/sh

. libtest.sh
. libgit.sh

first=...aaaaaaaaaaaaaaaa
second=aaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaa/aaaaaaaaaaaaaaaaaaaaaaaa/file
third=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt

steps '
	:view-main
	:1
	:view-stage
	:2
	:exec !assert-var "%(file)" == "'$second'"
	:status-update
'

in_work_dir git init -q .
in_work_dir git_config
in_work_dir git_add tracked base
in_work_dir git_commit --author="$IDENT_A" --message="Initial commit"
in_work_dir mkdir -p "$(dirname "$second")"
in_work_dir touch "$first" "$second" "$third"
in_work_dir git add "$first" "$second" "$third"

test_tig status
assert_vars 1
in_work_dir git status --short > git-status.out
assert_equals git-status.out <<EOF_STATUS
A  $first
A  $third
?? aaaaaaaaaaaaaaaaaaaaaaaa/
EOF_STATUS
