#!/bin/sh

. libtest.sh
. libgit.sh

steps '
	:view-main
	:1
	:view-stage
	:1
	:exec !assert-var "%(file)" == "touch file"
	:status-update
	:view-close
	:view-main
	:1
	:view-stage
	:status-update-all
'

in_work_dir git init -q .
in_work_dir git_config
in_work_dir git_add tracked base
in_work_dir git_commit --author="$IDENT_A" --message="Initial commit"
in_work_dir touch touch_file "touch file"

test_tig status

assert_vars 1

in_work_dir git status --short > git-status.out

assert_equals 'git-status.out' <<EOF_STATUS
A  touch file
A  touch_file
EOF_STATUS
