#!/bin/sh

. libtest.sh
. libgit.sh

steps '
	:/Untracked files:
	:j
	:status-update-all
'

in_work_dir git init -q .
in_work_dir git_config
in_work_dir git_add tracked
in_work_dir git_commit --author="$IDENT_A" --message="Initial commit"
in_work_dir touch foo bar

test_tig status

in_work_dir git status --short -z | tr '\0' '\n' > git-status.out

assert_equals 'git-status.out' <<EOF_STATUS
A  bar
A  foo
EOF_STATUS
